import axios from "axios";
import type { NextApiRequest, NextApiResponse } from "next";

type Data = {
  id: number;
  store: {
    logo: string;
    name: string;
    slug: string;
    url: string;
  };
  freight: string;
  subcategory: {
    category: {
      name: string;
    };
  };
  form_payment: string;
  title: string;
  slug: string;
  old_price: string;
  price: string;
  image: string;
  image_social: string;
  long_url: string;
  short_url: string;
  coupon: string;
};

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  const ofertasD = <any>[
    {
      id: 475,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Supermercado",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:52:22.597028-03:00",
      saved: [],
      title: "Repelente Elétrico Líquido SBP 45 Noites Novo Aparelho + Refil",
      slug: "repelente-eletrico-liquido-45-noites-kit-com-aparelho-e-refil-sbp",
      old_price: "15.99",
      price: "11.65",
      image:
        "https://admin.pechinchou.com.br/media/img/products/repelente-eletrico-liquido-45-noites-kit-com-aparelho-e-refil-sbp.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/photo_2022-03-07_21-13-16_Whk3XEl_DjxBrUB_4a2m05K_XYQn6GT_bDqR1yb_Wo0xTFj.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/gp/product/B07DZ9TWLX/?tag=parceiropechi-20",
      short_url: "https://amzn.to/30fkJZu",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "repelenteeletricoliquidosbp45noitesnovoaparelhorefil",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 1,
      likes: [
        26, 2, 10, 445, 24624, 32525, 50418, 57203, 30280, 113688, 123774,
        125827, 106380, 127438, 127760, 4366, 134531, 125602, 135438,
      ],
    },
    {
      id: 25244,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/280605858_5165428773578302_477379730123028679_n.jpg",
        name: "Americanas",
        slug: "americanas",
        url: "https://www.americanas.com.br/",
      },
      freight: "Retire na loja e não pague frete",
      warning: null,
      user_fake: {
        username: "Luis Lucilandio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/f088f479-c0e5-4dd1-8e11-c5c3326fd60c.png",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Saúde",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:43:46.916452-03:00",
      saved: [],
      title:
        "Carga para Aparelho de Barbear Gillette Mach3 Sensitive Leve 4 Pague 3",
      slug: "carga-para-aparelho-de-barbear-gillette-mach3-sensitive-leve-4-pague-3",
      old_price: "49.90",
      price: "23.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_30_7x8zgJs.jpg",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/WHATS_A_34_yWzNiKC_DeZqvZw_NNWM2Qh_biDcXuj_Vh0TFhx_gfQ3A9H_oFNSQml_HfabJPo_oSKgGPD_r7vWDmd_XD5Zhsq_DitKzs4_fh7F9Zn_dVMjwQS_bOnKkBc_q6JVUXw_nACfgR1_EmQCro7_MfK78LY_pm3hAUT.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.awin1.com/cread.php?awinmid=22193&awinaffid=902797&ued=https://www.americanas.com.br/produto/2489723140",
      short_url: "https://bit.ly/3EUm9ej",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: false,
      friend_pechinchou: true,
      treated_title:
        "cargaparaaparelhodebarbeargillettemach3sensitiveleve4pague3",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 16,
      likes: [],
    },
    {
      id: 22154,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: "Retire na loja e não pague frete",
      warning: null,
      user_fake: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Eletroportáteis",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:39:59.139433-03:00",
      saved: [],
      title: "Batedeira Portátil Preta 500W PBT510P - 4 Velocidades",
      slug: "batedeira-portatil-preta-500w-pbt510p-4-velocidades",
      old_price: "419.90",
      price: "195.02",
      image:
        "https://admin.pechinchou.com.br/media/img/products/batedeira-portatil-preta-500w-pbt510p-4-velocidades.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/WHATS_H_-_2022-08-22T191638_nmKneBp_BZo5474_Gy9FmLS_J4MmdWC_8OYL3Tx.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/batedeira-portatil-preta-500w-pbt510p-4-velocidades/p/222057500/EP/BAMA",
      short_url: "https://bit.ly/3CsZ4Ov",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "batedeiraportatilpreta500wpbt510p4velocidades",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 13,
      likes: [
        154108, 159322, 1214, 161917, 10, 2, 134849, 148540, 148811, 152574,
        140195, 155556, 158965, 161166, 174481, 222406,
      ],
    },
    {
      id: 31393,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      user: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      subcategory: {
        category: {
          name: "Eletrodomésticos",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:36:56.521719-03:00",
      saved: [],
      title: "Cooktop 1 Boca de Indução Midea CYAD11 Portátil Preto 110V",
      slug: "cooktop-1-boca-de-inducao-midea-cyad11-portatil-preto-110v",
      old_price: "369.00",
      price: "239.36",
      image:
        "https://admin.pechinchou.com.br/media/img/products/cooktop-1-boca-de-inducao-midea-cyad11-portatil-preto-110v.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/cooktop-1-boca-de-inducao-midea-cyad11-portatil-preto-110v/p/gd37279930",
      short_url: "https://bit.ly/3hj7waP",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "cooktop1bocadeinducaomideacyad11portatilpreto110v",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 15,
      likes: [10],
    },
    {
      id: 5730,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/280605858_5165428773578302_477379730123028679_n.jpg",
        name: "Americanas",
        slug: "americanas",
        url: "https://www.americanas.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "mariaisadora",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/IMG-20220520-WA0198.jpg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Televisão",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T21:29:42.181171-03:00",
      saved: [],
      title:
        'Smart TV 60" UHD 4K Samsung 60AU7700 Processador Crystal 4K Tela sem Limites Visual Livre de Cabos Alexa Built in Controle Único',
      slug: "smart-tv-60-uhd-4k-samsung-60au7700-processador-crystal-4k-tela-sem-limites-visual-livre-de-cabos-alexa-built-in-controle-unico",
      old_price: "3777.00",
      price: "3099.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_26_u3ggTZ6.jpg",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/photo_2022-11-28_14-59-46_SEH2WeM_zG5aPoy_BhgRu3y_U7AWxYE_sgiGRxf_GT8ETVT_nDh7jwR_SCRa8uk_mGS0GBI_Rhjpmto_HlbNals_iCKeesX_jejDSaF_nwQTgDm_4zwzwmC.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.awin1.com/cread.php?awinmid=22193&awinaffid=902797&ued=https://www.americanas.com.br/produto/3480206525?sellerId=00776574000660",
      short_url: "https://bit.ly/3XGzApa",
      coupon: "",
      warning_temp: null,
      ame: true,
      ame_attribute: {
        percentage: 10.0,
        price: 3099.99,
        portion: 8.0,
        discount: 310.0,
      },
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: true,
      friend_pechinchou: true,
      treated_title:
        "smarttv60uhd4ksamsung60au7700processadorcrystal4ktelasemlimitesvisuallivredecabosalexabuiltincontroleunico",
      is_image_social: false,
      resize_image_tam:
        'Smart TV 60" UHD Samsung 4k 60AU7700 Processador Crystal 4k',
      alertcomment: 1,
      likes: [10, 445, 204, 211760, 214852, 180804, 218857],
    },
    {
      id: 28128,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "leofabricio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/122964120_3789462247739716_4153710995915978761_n.jpg",
      },
      user: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      subcategory: {
        category: {
          name: "Esporte e Lazer",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T21:27:08.701355-03:00",
      saved: [],
      title: "Bicicleta Aro 29 KRW Alumínio 24 Vel Freio a Disco Hidráulico R6",
      slug: "bicicleta-aro-29-krw-aluminio-24-vel-freio-a-disco-hidraulico-r6",
      old_price: "1899.00",
      price: "1199.00",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_321.jpg",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/bicicleta-aro-29-krw-aluminio-24-vel-freio-a-disco-hidraulico-r6/p/jek9k6c0e1",
      short_url: "https://bit.ly/3UKtrpd",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "bicicletaaro29krwaluminio24velfreioadiscohidraulicor6",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 2,
      likes: [116022, 10],
    },
    {
      id: 21245,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "Jonhy Everton",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-09-01_at_09.16.15.jpeg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Supermercado",
        },
      },
      form_payment: "À vista",
      total_comment: 5,
      created_at: "2022-12-09T21:26:31.984268-03:00",
      saved: [],
      title: "Sabonete Líquido Palmolive Nutri-Milk Hidratante 250Ml",
      slug: "sabonete-liquido-palmolive-nutri-milk-hidratante-250ml",
      old_price: "7.72",
      price: "5.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/sabonete-liquido-palmolive-nutri-milk-hidratante-250ml.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/ARQUIVO_-_CLEITON_782750px_-_2022-10-09T171826_NMAJdxb_4Ok49Lg_uo6WhV5_EUAPbPB_9H5dRm8_z6qakFs_3hw7xm1_hNnKf56_q0HeYXA_8l3nRAw_jjaGfgp_RYv8oG2_qEm8olU_pNM49VJ_KNk5qvu_IFoHPbj_458aeCm_USbY4Uv_SH8gJN7_Tn1oqAZ_46EWgPC_VIRIQIP__rhBP1x6.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/social/ARQUIVO_-_CLEITON_782750px_-_2022-10-09T171826_NMAJdxb_4Ok49Lg_uo6WhV5_EUAPbPB_9H5dRm8_z6qakFs_3hw7xm1_hNnKf56_q0HeYXA_8l3nRAw_jjaGfgp_RYv8oG2_qEm8olU_pNM49VJ_KNk5qvu_IFoHPbj_458aeCm_USbY4Uv_SH8gJN7_Tn1oqAZ_46EWgPC_VIRIQIP__rhBP1x6.jpg",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url: "https://www.amazon.com.br/dp/B07G5XW7HT/?tag=parceiropechi-20",
      short_url: "https://amzn.to/3QjRDg7",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: false,
      friend_pechinchou: true,
      treated_title: "saboneteliquidopalmolivenutrimilkhidratante250ml",
      is_image_social: true,
      resize_image_tam: null,
      alertcomment: 1,
      likes: [
        154226, 26538, 123888, 10, 59567, 2, 150988, 157204, 117934, 175280,
        9049, 185292, 179679, 216064, 218737, 216201, 87830, 179298,
      ],
    },
    {
      id: 31392,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "leandrogustavo",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/editada.png",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Supermercado",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:26:27.463310-03:00",
      saved: [],
      title:
        "Aromatizador de Ambiente Capim-Limão 165 ml Difusor com 5 Varetas, Salutar",
      slug: "aromatizador-de-ambiente-capim-limao-165-ml-difusor-com-5-varetas-salutar",
      old_price: "33.30",
      price: "24.10",
      image:
        "https://admin.pechinchou.com.br/media/img/products/aromatizador-de-ambiente-capim-limao-165-ml-difusor-com-5-varetas-salutar.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/Difusor-Aroma-Capim-Lim%C3%A3o-Varetas-Salutar/dp/B0942BJRCP/?tag=parceiropechi-20",
      short_url: "https://amzn.to/3hdbGky",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title:
        "aromatizadordeambientecapimlimao165mldifusorcom5varetassalutar",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 13,
      likes: [10],
    },
    {
      id: 31391,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "Luis Lucilandio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/f088f479-c0e5-4dd1-8e11-c5c3326fd60c.png",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Saúde",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:21:36.052682-03:00",
      saved: [],
      title: "Protetor Solar Facial ISDIN Fusion Water 5 Stars FPS 60 - 30ml",
      slug: "protetor-solar-facial-isdin-fusion-water-5-stars-fps-60-30ml-w3si",
      old_price: "88.59",
      price: "49.12",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_13_OMii8Ax.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/306081300_2637337106403235_4383892651232556586_n_0ibC7ZT_7qmrVUH_anllQyd_wdDgxis_SLvhx9V_mSmVv9M_H3NNHug_Ey2aTHi_dYkhgSv_OekbzI8_gOHUmOY_uyrDmXZ.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/magazinepromosnahora/protetor-solar-facial-isdin-fusion-water-oil-control-fps-60-com-30ml/p/hhf13b2dd2/pf/psfc",
      short_url: "https://bit.ly/3PfolQE",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "protetorsolarfacialisdinfusionwater5starsfps6030ml",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 1,
      likes: [10],
    },
    {
      id: 19484,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: "Frete Grátis todo o Brasil",
      warning: null,
      user_fake: {
        username: "pablolira",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/fa588a3c-d3e1-4447-922d-1b1b32691071.jpg",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "À vista",
      total_comment: 2,
      created_at: "2022-12-09T21:19:21.113267-03:00",
      saved: [],
      title: "Slip On Santa Lolla Jeans Logo Feminino",
      slug: "slip-on-santa-lolla-jeans-logo-feminino",
      old_price: "119.99",
      price: "69.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_42_uf5oS2H.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_C%C3%B3pia_de_C%C3%B3pia_de_FOTO_WHATS_JgMsp37_n5vut3u_1wOc6Ev_iWHzTEu_8A8Ndmu_ssfo0Xi_G9rvm4f_ZkK1jzX_orcV3hJ_hppxyfp_f8hESa0_kgfe2KK_mK88ofe_4AIN15F_XZTTL7W_ltgZaHR_PWxJ2Xu_ny9Vy5G_FBKcUgy_ccliK14_4wrKYQy_r2qoYb9_7qqWUWg_b_rURFNUD.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_C%C3%B3pia_de_C%C3%B3pia_de_FOTO_WHATS_JgMsp37_n5vut3u_1wOc6Ev_iWHzTEu_8A8Ndmu_ssfo0Xi_G9rvm4f_ZkK1jzX_orcV3hJ_hppxyfp_f8hESa0_kgfe2KK_mK88ofe_4AIN15F_XZTTL7W_ltgZaHR_PWxJ2Xu_ny9Vy5G_FBKcUgy_ccliK14_4wrKYQy_r2qoYb9_7qqWUWg_b_rURFNUD.jpg",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/slip-on-santa-lolla-jeans-logo-feminino/p/bba8252f1c",
      short_url: "https://bit.ly/3QODyZ8",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "sliponsantalollajeanslogofeminino",
      is_image_social: true,
      resize_image_tam: null,
      alertcomment: 1,
      likes: [
        19515, 76036, 32590, 76260, 81465, 89053, 10, 121228, 1, 127053, 132643,
        138760, 155545, 130370, 158082, 174481, 177089, 177095, 179333, 187425,
        190816, 190940, 196006, 210054, 194704,
      ],
    },
    {
      id: 31389,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/280605858_5165428773578302_477379730123028679_n.jpg",
        name: "Americanas",
        slug: "americanas",
        url: "https://www.americanas.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "leofabricio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/122964120_3789462247739716_4153710995915978761_n.jpg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T21:08:23.890059-03:00",
      saved: [],
      title: "Escova Secadora Philco PEC09RG Soft Beauty Rose - 220V",
      slug: "escova-secadora-philco-pec09rg-soft-beauty-rose-220v",
      old_price: "189.90",
      price: "129.97",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_23_OQzry2s.jpg",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_WHATS_A_16_84DL5Rb_kwJ3ygG_TgNmet8_rGi1Dpv_WVSpKGu_p0coynl.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.awin1.com/cread.php?awinmid=22193&awinaffid=902797&ued=https://www.americanas.com.br/produto/134209926",
      short_url: "https://bit.ly/3VDNy9P",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: true,
      friend_pechinchou: true,
      treated_title: "escovasecadoraphilcopec09rgsoftbeautyrose220v",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 8,
      likes: [10],
    },
    {
      id: 23318,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "jonhyeverton",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-09-01_at_09.16.15_pY3S8pH.jpeg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Supermercado",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:02:39.256317-03:00",
      saved: [],
      title:
        "Creme Para Pentear Reparação Total 5 Extra Profundo Elseve L'Oréal Paris 250 ml, L'Oréal Paris, Branco, 250ML",
      slug: "creme-para-pentear-reparacao-total-5-extra-profundo-elseve-loreal-paris-250-ml-loreal-paris-branco-250ml",
      old_price: "14.99",
      price: "12.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/creme-para-pentear-reparacao-total-5-extra-profundo-elseve-loreal-paris-250-ml-loreal-paris-branco-250ml.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/dp/B07G2WFKTC?th=1&tag=parceiropechi-20",
      short_url: "https://amzn.to/3SjE4yn",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title:
        "cremeparapentearreparacaototal5extraprofundoelsevelorealparis250mllorealparisbranco250ml",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 15,
      likes: [2, 10],
    },
    {
      id: 27300,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "laryssa_mfelix",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/179491832_721224289258970_9223007346925788281_n.jpg",
      },
      user: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      subcategory: {
        category: {
          name: "Games",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:01:13.135958-03:00",
      saved: [],
      title:
        "Microfone Gamer HyperX QuadCast, Antivibração, LED, Preto e Vermelho, Compatível com PC, Mac e Consoles - HX-MICQC-BK",
      slug: "microfone-gamer-hyperx-quadcast-antivibracao-led-preto-e-vermelho-compativel-com-pc-mac-e-consoles-hx-micqc-bk-tdy3",
      old_price: "960.49",
      price: "699.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/microfone-gamer-hyperx-quadcast-antivibracao-led-preto-e-vermelho-compativel-com-pc-mac-e-consoles-hx-micqc-bk-tdy3.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/microfone-gamer-hyperx-quadcast-antivibracao-led-preto-e-vermelho-compativel-com-pc-mac-e-consoles-hx-micqc-bk/p/hgda4bfc7c/IN/MICG",
      short_url: "https://bit.ly/3A8AMrf",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title:
        "microfonegamerhyperxquadcastantivibracaoledpretoevermelhocompativelcompcmaceconsoleshxmicqcbk",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 16,
      likes: [213791, 10],
    },
    {
      id: 7753,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Casas_bahia.png",
        name: "Casas Bahia",
        slug: "casas-bahia",
        url: "https://www.casasbahia.com.br/",
      },
      freight: "Frete Grátis todo o Brasil",
      warning: null,
      user_fake: {
        username: "pablolira",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/fa588a3c-d3e1-4447-922d-1b1b32691071.jpg",
      },
      user: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T21:00:20.890175-03:00",
      saved: [],
      title: "Escova Secadora Cadence Rouge Style ESC700 127V",
      slug: "escova-secadora-cadence-rouge-style-esc700-127v",
      old_price: "119.90",
      price: "89.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_1_CmnKFYE.jpg",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/270377688_1388332594935646_1630532231340850097_n_SOe1qbP_PQuZzm3_hIKdmSA_bh29Y9q_HlKjvVE_dFm7ZGz.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/social/270377688_1388332594935646_1630532231340850097_n_SOe1qbP_PQuZzm3_hIKdmSA_bh29Y9q_HlKjvVE_dFm7ZGz.jpg",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.awin1.com/cread.php?awinmid=17629&awinaffid=667997&ued=https://www.casasbahia.com.br/escova-secadora-cadence-rouge-style-esc700-127v-1515113217.html",
      short_url: "https://bit.ly/3HGDOHV",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "escovasecadoracadencerougestyleesc700127v",
      is_image_social: true,
      resize_image_tam: null,
      alertcomment: 1,
      likes: [1214, 445, 2, 10, 215563, 221360],
    },
    {
      id: 31388,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/06/Rectangle_413_4.png",
        name: "Shoptime",
        slug: "shoptime",
        url: "https://www.shoptime.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "Jonhy Everton",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-09-01_at_09.16.15.jpeg",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Supermercado",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T20:57:28.543581-03:00",
      saved: [],
      title: "Sabão Liquido Brilhante Delicadeza Total Coco 3L",
      slug: "sabao-liquido-brilhante-delicadeza-total-coco-3l",
      old_price: "34.99",
      price: "26.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_12_odNg8O3.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.awin1.com/cread.php?awinmid=22194&awinaffid=902797&ued=https://www.shoptime.com.br/produto/1960474342",
      short_url: "https://bit.ly/3iTgKeB",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "sabaoliquidobrilhantedelicadezatotalcoco3l",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 2,
      likes: [10],
    },
    {
      id: 31387,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "Jonhy Everton",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-09-01_at_09.16.15.jpeg",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T20:54:13.197327-03:00",
      saved: [],
      title: "Kit 3 Bolsas Média Pequena e Carteira Couro Sintético ShopBag",
      slug: "kit-3-bolsas-media-pequena-e-carteira-couro-sintetico-shopbag",
      old_price: "129.99",
      price: "99.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/kit-3-bolsas-media-pequena-e-carteira-couro-sintetico-shopbag.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url: "https://www.amazon.com.br/dp/B09RKQY7CQ/?tag=parceiropechi-20",
      short_url: "https://amzn.to/3Y9nODY",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "kit3bolsasmediapequenaecarteiracourosinteticoshopbag",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 14,
      likes: [10],
    },
    {
      id: 30684,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "jonhyeverton",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-09-01_at_09.16.15_pY3S8pH.jpeg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T20:51:32.682794-03:00",
      saved: [],
      title: "Chinelo Top Animals, Havaianas, Feminino",
      slug: "chinelo-top-animals-havaianas-feminino-exk8",
      old_price: "23.99",
      price: "18.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/71oD-VxmRL._AC_SL1000_.jpg",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/Chinelo-Animals-Havaianas-Feminino-Branco/dp/B094PV267S/?tag=parceiropechi-20",
      short_url: "https://amzn.to/3gQYP7I",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "chinelotopanimalshavaianasfeminino",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 9,
      likes: [216064, 216983, 10],
    },
    {
      id: 31386,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "laryssa_mfelix",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/179491832_721224289258970_9223007346925788281_n.jpg",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Bebidas",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T20:51:19.544124-03:00",
      saved: [],
      title:
        "Perfume Importado Paris Elysees Eau De Toilette Masculino Vodka Limited Edition 100ml",
      slug: "perfume-importado-paris-elysees-eau-de-toilette-masculino-vodka-limited-edition-100ml",
      old_price: "69.00",
      price: "54.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/perfume-importado-paris-elysees-eau-de-toilette-masculino-vodka-limited-edition-100ml.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_WHATS_A_15_VTwwjZ9_OzNUbqG_LmSFAJ2_QMRfqUQ_ENkL6oE_ER52O4A_QhccK1q_z9OJ2Vt.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/real/C%C3%B3pia_de_WHATS_A_15.png",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/Vodka-Limited-Masculino-Paris-Elysees/dp/B008VDH6W8/?tag=parceiropechi-20",
      short_url: "https://amzn.to/3HlAPo1",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: true,
      friend_pechinchou: true,
      treated_title:
        "perfumeimportadopariselyseeseaudetoilettemasculinovodkalimitededition100ml",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 12,
      likes: [10, 32104],
    },
    {
      id: 30680,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "leofabricio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/122964120_3789462247739716_4153710995915978761_n.jpg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T20:37:36.666656-03:00",
      saved: [],
      title: "Rasteira You Metalic, Havaianas, Feminino",
      slug: "rasteira-you-metalic-havaianas-feminino",
      old_price: "55.99",
      price: "34.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/rasteira-you-metalic-havaianas-feminino.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_WHATS_A_49_mlP5gqu_AYoCSWc_HnrkiFW_rbTF0no_Bw6R0Be_ASrZmCK_bDkTVUO.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/real/C%C3%B3pia_de_WHATS_A_49.png",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/dp/B094PV11YP?th=1&psc=1&tag=parceiropechi-20",
      short_url: "https://amzn.to/3iw4pwF",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "rasteirayoumetalichavaianasfeminino",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 11,
      likes: [10],
    },
    {
      id: 31385,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/06/Rectangle_413_10.png",
        name: "Centauro",
        slug: "centauro",
        url: "https://www.centauro.com.br/",
      },
      freight: "Frete Grátis todo o Brasil",
      warning: null,
      user_fake: {
        username: "leofabricio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/122964120_3789462247739716_4153710995915978761_n.jpg",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T20:35:02.652952-03:00",
      saved: [],
      title: "Tênis Fila Racer Marker Feminino - Preto+Pink",
      slug: "tenis-fila-racer-marker-feminino-pretopink",
      old_price: "399.99",
      price: "254.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_11_fcTffdB.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_WHATS_A_14_rpEoytR_aQd0Osl_0DMWP8A_hHBdVfg_jcy7B4x_sodq1yA_xv9zDIZ_VFpV19D_gVuJeBA.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/real/C%C3%B3pia_de_WHATS_A_14_dJQWrs2.png",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://click.linksynergy.com/deeplink?id=ILc7vlXm*ug&mid=39887&murl=https://www.centauro.com.br/tenis-fila-racer-marker-feminino-975812.html#cor=FP",
      short_url: "https://bit.ly/3Y9lkp8",
      coupon: "TENISCERTO15",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: true,
      friend_pechinchou: true,
      treated_title: "tenisfilaracermarkerfemininopretopink",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 13,
      likes: [10],
    },
  ];
  const ofertasRef = <any>[
    {
      id: 475,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Supermercado",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:52:22.597028-03:00",
      saved: [],
      title: "Repelente Elétrico Líquido SBP 45 Noites Novo Aparelho + Refil",
      slug: "repelente-eletrico-liquido-45-noites-kit-com-aparelho-e-refil-sbp",
      old_price: "15.99",
      price: "11.65",
      image:
        "https://admin.pechinchou.com.br/media/img/products/repelente-eletrico-liquido-45-noites-kit-com-aparelho-e-refil-sbp.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/photo_2022-03-07_21-13-16_Whk3XEl_DjxBrUB_4a2m05K_XYQn6GT_bDqR1yb_Wo0xTFj.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/gp/product/B07DZ9TWLX/?tag=parceiropechi-20",
      short_url: "https://amzn.to/30fkJZu",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "repelenteeletricoliquidosbp45noitesnovoaparelhorefil",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 1,
      likes: [
        26, 2, 10, 445, 24624, 32525, 50418, 57203, 30280, 113688, 123774,
        125827, 106380, 127438, 127760, 4366, 134531, 125602, 135438,
      ],
    },
    {
      id: 25244,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/280605858_5165428773578302_477379730123028679_n.jpg",
        name: "Americanas",
        slug: "americanas",
        url: "https://www.americanas.com.br/",
      },
      freight: "Retire na loja e não pague frete",
      warning: null,
      user_fake: {
        username: "Luis Lucilandio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/f088f479-c0e5-4dd1-8e11-c5c3326fd60c.png",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Saúde",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:43:46.916452-03:00",
      saved: [],
      title:
        "Carga para Aparelho de Barbear Gillette Mach3 Sensitive Leve 4 Pague 3",
      slug: "carga-para-aparelho-de-barbear-gillette-mach3-sensitive-leve-4-pague-3",
      old_price: "49.90",
      price: "23.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_30_7x8zgJs.jpg",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/WHATS_A_34_yWzNiKC_DeZqvZw_NNWM2Qh_biDcXuj_Vh0TFhx_gfQ3A9H_oFNSQml_HfabJPo_oSKgGPD_r7vWDmd_XD5Zhsq_DitKzs4_fh7F9Zn_dVMjwQS_bOnKkBc_q6JVUXw_nACfgR1_EmQCro7_MfK78LY_pm3hAUT.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.awin1.com/cread.php?awinmid=22193&awinaffid=902797&ued=https://www.americanas.com.br/produto/2489723140",
      short_url: "https://bit.ly/3EUm9ej",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: false,
      friend_pechinchou: true,
      treated_title:
        "cargaparaaparelhodebarbeargillettemach3sensitiveleve4pague3",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 16,
      likes: [],
    },
    {
      id: 22154,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: "Retire na loja e não pague frete",
      warning: null,
      user_fake: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Eletroportáteis",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:39:59.139433-03:00",
      saved: [],
      title: "Batedeira Portátil Preta 500W PBT510P - 4 Velocidades",
      slug: "batedeira-portatil-preta-500w-pbt510p-4-velocidades",
      old_price: "419.90",
      price: "195.02",
      image:
        "https://admin.pechinchou.com.br/media/img/products/batedeira-portatil-preta-500w-pbt510p-4-velocidades.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/WHATS_H_-_2022-08-22T191638_nmKneBp_BZo5474_Gy9FmLS_J4MmdWC_8OYL3Tx.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/batedeira-portatil-preta-500w-pbt510p-4-velocidades/p/222057500/EP/BAMA",
      short_url: "https://bit.ly/3CsZ4Ov",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "batedeiraportatilpreta500wpbt510p4velocidades",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 13,
      likes: [
        154108, 159322, 1214, 161917, 10, 2, 134849, 148540, 148811, 152574,
        140195, 155556, 158965, 161166, 174481, 222406,
      ],
    },
    {
      id: 31393,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      user: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      subcategory: {
        category: {
          name: "Eletrodomésticos",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:36:56.521719-03:00",
      saved: [],
      title: "Cooktop 1 Boca de Indução Midea CYAD11 Portátil Preto 110V",
      slug: "cooktop-1-boca-de-inducao-midea-cyad11-portatil-preto-110v",
      old_price: "369.00",
      price: "239.36",
      image:
        "https://admin.pechinchou.com.br/media/img/products/cooktop-1-boca-de-inducao-midea-cyad11-portatil-preto-110v.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/cooktop-1-boca-de-inducao-midea-cyad11-portatil-preto-110v/p/gd37279930",
      short_url: "https://bit.ly/3hj7waP",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "cooktop1bocadeinducaomideacyad11portatilpreto110v",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 15,
      likes: [10],
    },
    {
      id: 5730,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/280605858_5165428773578302_477379730123028679_n.jpg",
        name: "Americanas",
        slug: "americanas",
        url: "https://www.americanas.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "mariaisadora",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/IMG-20220520-WA0198.jpg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Televisão",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T21:29:42.181171-03:00",
      saved: [],
      title:
        'Smart TV 60" UHD 4K Samsung 60AU7700 Processador Crystal 4K Tela sem Limites Visual Livre de Cabos Alexa Built in Controle Único',
      slug: "smart-tv-60-uhd-4k-samsung-60au7700-processador-crystal-4k-tela-sem-limites-visual-livre-de-cabos-alexa-built-in-controle-unico",
      old_price: "3777.00",
      price: "3099.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_26_u3ggTZ6.jpg",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/photo_2022-11-28_14-59-46_SEH2WeM_zG5aPoy_BhgRu3y_U7AWxYE_sgiGRxf_GT8ETVT_nDh7jwR_SCRa8uk_mGS0GBI_Rhjpmto_HlbNals_iCKeesX_jejDSaF_nwQTgDm_4zwzwmC.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.awin1.com/cread.php?awinmid=22193&awinaffid=902797&ued=https://www.americanas.com.br/produto/3480206525?sellerId=00776574000660",
      short_url: "https://bit.ly/3XGzApa",
      coupon: "",
      warning_temp: null,
      ame: true,
      ame_attribute: {
        percentage: 10.0,
        price: 3099.99,
        portion: 8.0,
        discount: 310.0,
      },
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: true,
      friend_pechinchou: true,
      treated_title:
        "smarttv60uhd4ksamsung60au7700processadorcrystal4ktelasemlimitesvisuallivredecabosalexabuiltincontroleunico",
      is_image_social: false,
      resize_image_tam:
        'Smart TV 60" UHD Samsung 4k 60AU7700 Processador Crystal 4k',
      alertcomment: 1,
      likes: [10, 445, 204, 211760, 214852, 180804, 218857],
    },
    {
      id: 28128,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "leofabricio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/122964120_3789462247739716_4153710995915978761_n.jpg",
      },
      user: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      subcategory: {
        category: {
          name: "Esporte e Lazer",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T21:27:08.701355-03:00",
      saved: [],
      title: "Bicicleta Aro 29 KRW Alumínio 24 Vel Freio a Disco Hidráulico R6",
      slug: "bicicleta-aro-29-krw-aluminio-24-vel-freio-a-disco-hidraulico-r6",
      old_price: "1899.00",
      price: "1199.00",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_321.jpg",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/bicicleta-aro-29-krw-aluminio-24-vel-freio-a-disco-hidraulico-r6/p/jek9k6c0e1",
      short_url: "https://bit.ly/3UKtrpd",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "bicicletaaro29krwaluminio24velfreioadiscohidraulicor6",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 2,
      likes: [116022, 10],
    },
    {
      id: 21245,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "Jonhy Everton",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-09-01_at_09.16.15.jpeg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Supermercado",
        },
      },
      form_payment: "À vista",
      total_comment: 5,
      created_at: "2022-12-09T21:26:31.984268-03:00",
      saved: [],
      title: "Sabonete Líquido Palmolive Nutri-Milk Hidratante 250Ml",
      slug: "sabonete-liquido-palmolive-nutri-milk-hidratante-250ml",
      old_price: "7.72",
      price: "5.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/sabonete-liquido-palmolive-nutri-milk-hidratante-250ml.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/ARQUIVO_-_CLEITON_782750px_-_2022-10-09T171826_NMAJdxb_4Ok49Lg_uo6WhV5_EUAPbPB_9H5dRm8_z6qakFs_3hw7xm1_hNnKf56_q0HeYXA_8l3nRAw_jjaGfgp_RYv8oG2_qEm8olU_pNM49VJ_KNk5qvu_IFoHPbj_458aeCm_USbY4Uv_SH8gJN7_Tn1oqAZ_46EWgPC_VIRIQIP__rhBP1x6.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/social/ARQUIVO_-_CLEITON_782750px_-_2022-10-09T171826_NMAJdxb_4Ok49Lg_uo6WhV5_EUAPbPB_9H5dRm8_z6qakFs_3hw7xm1_hNnKf56_q0HeYXA_8l3nRAw_jjaGfgp_RYv8oG2_qEm8olU_pNM49VJ_KNk5qvu_IFoHPbj_458aeCm_USbY4Uv_SH8gJN7_Tn1oqAZ_46EWgPC_VIRIQIP__rhBP1x6.jpg",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url: "https://www.amazon.com.br/dp/B07G5XW7HT/?tag=parceiropechi-20",
      short_url: "https://amzn.to/3QjRDg7",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: false,
      friend_pechinchou: true,
      treated_title: "saboneteliquidopalmolivenutrimilkhidratante250ml",
      is_image_social: true,
      resize_image_tam: null,
      alertcomment: 1,
      likes: [
        154226, 26538, 123888, 10, 59567, 2, 150988, 157204, 117934, 175280,
        9049, 185292, 179679, 216064, 218737, 216201, 87830, 179298,
      ],
    },
    {
      id: 31392,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "leandrogustavo",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/editada.png",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Supermercado",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:26:27.463310-03:00",
      saved: [],
      title:
        "Aromatizador de Ambiente Capim-Limão 165 ml Difusor com 5 Varetas, Salutar",
      slug: "aromatizador-de-ambiente-capim-limao-165-ml-difusor-com-5-varetas-salutar",
      old_price: "33.30",
      price: "24.10",
      image:
        "https://admin.pechinchou.com.br/media/img/products/aromatizador-de-ambiente-capim-limao-165-ml-difusor-com-5-varetas-salutar.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/Difusor-Aroma-Capim-Lim%C3%A3o-Varetas-Salutar/dp/B0942BJRCP/?tag=parceiropechi-20",
      short_url: "https://amzn.to/3hdbGky",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title:
        "aromatizadordeambientecapimlimao165mldifusorcom5varetassalutar",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 13,
      likes: [10],
    },
    {
      id: 31391,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "Luis Lucilandio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/f088f479-c0e5-4dd1-8e11-c5c3326fd60c.png",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Saúde",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:21:36.052682-03:00",
      saved: [],
      title: "Protetor Solar Facial ISDIN Fusion Water 5 Stars FPS 60 - 30ml",
      slug: "protetor-solar-facial-isdin-fusion-water-5-stars-fps-60-30ml-w3si",
      old_price: "88.59",
      price: "49.12",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_13_OMii8Ax.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/306081300_2637337106403235_4383892651232556586_n_0ibC7ZT_7qmrVUH_anllQyd_wdDgxis_SLvhx9V_mSmVv9M_H3NNHug_Ey2aTHi_dYkhgSv_OekbzI8_gOHUmOY_uyrDmXZ.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/magazinepromosnahora/protetor-solar-facial-isdin-fusion-water-oil-control-fps-60-com-30ml/p/hhf13b2dd2/pf/psfc",
      short_url: "https://bit.ly/3PfolQE",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "protetorsolarfacialisdinfusionwater5starsfps6030ml",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 1,
      likes: [10],
    },
    {
      id: 19484,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: "Frete Grátis todo o Brasil",
      warning: null,
      user_fake: {
        username: "pablolira",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/fa588a3c-d3e1-4447-922d-1b1b32691071.jpg",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "À vista",
      total_comment: 2,
      created_at: "2022-12-09T21:19:21.113267-03:00",
      saved: [],
      title: "Slip On Santa Lolla Jeans Logo Feminino",
      slug: "slip-on-santa-lolla-jeans-logo-feminino",
      old_price: "119.99",
      price: "69.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_42_uf5oS2H.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_C%C3%B3pia_de_C%C3%B3pia_de_FOTO_WHATS_JgMsp37_n5vut3u_1wOc6Ev_iWHzTEu_8A8Ndmu_ssfo0Xi_G9rvm4f_ZkK1jzX_orcV3hJ_hppxyfp_f8hESa0_kgfe2KK_mK88ofe_4AIN15F_XZTTL7W_ltgZaHR_PWxJ2Xu_ny9Vy5G_FBKcUgy_ccliK14_4wrKYQy_r2qoYb9_7qqWUWg_b_rURFNUD.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_C%C3%B3pia_de_C%C3%B3pia_de_FOTO_WHATS_JgMsp37_n5vut3u_1wOc6Ev_iWHzTEu_8A8Ndmu_ssfo0Xi_G9rvm4f_ZkK1jzX_orcV3hJ_hppxyfp_f8hESa0_kgfe2KK_mK88ofe_4AIN15F_XZTTL7W_ltgZaHR_PWxJ2Xu_ny9Vy5G_FBKcUgy_ccliK14_4wrKYQy_r2qoYb9_7qqWUWg_b_rURFNUD.jpg",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/slip-on-santa-lolla-jeans-logo-feminino/p/bba8252f1c",
      short_url: "https://bit.ly/3QODyZ8",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "sliponsantalollajeanslogofeminino",
      is_image_social: true,
      resize_image_tam: null,
      alertcomment: 1,
      likes: [
        19515, 76036, 32590, 76260, 81465, 89053, 10, 121228, 1, 127053, 132643,
        138760, 155545, 130370, 158082, 174481, 177089, 177095, 179333, 187425,
        190816, 190940, 196006, 210054, 194704,
      ],
    },
    {
      id: 31389,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/280605858_5165428773578302_477379730123028679_n.jpg",
        name: "Americanas",
        slug: "americanas",
        url: "https://www.americanas.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "leofabricio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/122964120_3789462247739716_4153710995915978761_n.jpg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T21:08:23.890059-03:00",
      saved: [],
      title: "Escova Secadora Philco PEC09RG Soft Beauty Rose - 220V",
      slug: "escova-secadora-philco-pec09rg-soft-beauty-rose-220v",
      old_price: "189.90",
      price: "129.97",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_23_OQzry2s.jpg",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_WHATS_A_16_84DL5Rb_kwJ3ygG_TgNmet8_rGi1Dpv_WVSpKGu_p0coynl.jpg",
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.awin1.com/cread.php?awinmid=22193&awinaffid=902797&ued=https://www.americanas.com.br/produto/134209926",
      short_url: "https://bit.ly/3VDNy9P",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: true,
      friend_pechinchou: true,
      treated_title: "escovasecadoraphilcopec09rgsoftbeautyrose220v",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 8,
      likes: [10],
    },
    {
      id: 23318,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "jonhyeverton",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-09-01_at_09.16.15_pY3S8pH.jpeg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Supermercado",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:02:39.256317-03:00",
      saved: [],
      title:
        "Creme Para Pentear Reparação Total 5 Extra Profundo Elseve L'Oréal Paris 250 ml, L'Oréal Paris, Branco, 250ML",
      slug: "creme-para-pentear-reparacao-total-5-extra-profundo-elseve-loreal-paris-250-ml-loreal-paris-branco-250ml",
      old_price: "14.99",
      price: "12.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/creme-para-pentear-reparacao-total-5-extra-profundo-elseve-loreal-paris-250-ml-loreal-paris-branco-250ml.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/dp/B07G2WFKTC?th=1&tag=parceiropechi-20",
      short_url: "https://amzn.to/3SjE4yn",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title:
        "cremeparapentearreparacaototal5extraprofundoelsevelorealparis250mllorealparisbranco250ml",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 15,
      likes: [2, 10],
    },
    {
      id: 27300,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Magalu0.png",
        name: "Magazine Luiza",
        slug: "magazine-luiza",
        url: "https://www.magazinevoce.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "laryssa_mfelix",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/179491832_721224289258970_9223007346925788281_n.jpg",
      },
      user: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      subcategory: {
        category: {
          name: "Games",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T21:01:13.135958-03:00",
      saved: [],
      title:
        "Microfone Gamer HyperX QuadCast, Antivibração, LED, Preto e Vermelho, Compatível com PC, Mac e Consoles - HX-MICQC-BK",
      slug: "microfone-gamer-hyperx-quadcast-antivibracao-led-preto-e-vermelho-compativel-com-pc-mac-e-consoles-hx-micqc-bk-tdy3",
      old_price: "960.49",
      price: "699.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/microfone-gamer-hyperx-quadcast-antivibracao-led-preto-e-vermelho-compativel-com-pc-mac-e-consoles-hx-micqc-bk-tdy3.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.magazinevoce.com.br/magazinedopechinchou/microfone-gamer-hyperx-quadcast-antivibracao-led-preto-e-vermelho-compativel-com-pc-mac-e-consoles-hx-micqc-bk/p/hgda4bfc7c/IN/MICG",
      short_url: "https://bit.ly/3A8AMrf",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title:
        "microfonegamerhyperxquadcastantivibracaoledpretoevermelhocompativelcompcmaceconsoleshxmicqcbk",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 16,
      likes: [213791, 10],
    },
    {
      id: 7753,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Casas_bahia.png",
        name: "Casas Bahia",
        slug: "casas-bahia",
        url: "https://www.casasbahia.com.br/",
      },
      freight: "Frete Grátis todo o Brasil",
      warning: null,
      user_fake: {
        username: "pablolira",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/fa588a3c-d3e1-4447-922d-1b1b32691071.jpg",
      },
      user: {
        username: "Andrier",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-05-03_at_13.09.58.jpeg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T21:00:20.890175-03:00",
      saved: [],
      title: "Escova Secadora Cadence Rouge Style ESC700 127V",
      slug: "escova-secadora-cadence-rouge-style-esc700-127v",
      old_price: "119.90",
      price: "89.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_1_CmnKFYE.jpg",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/270377688_1388332594935646_1630532231340850097_n_SOe1qbP_PQuZzm3_hIKdmSA_bh29Y9q_HlKjvVE_dFm7ZGz.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/social/270377688_1388332594935646_1630532231340850097_n_SOe1qbP_PQuZzm3_hIKdmSA_bh29Y9q_HlKjvVE_dFm7ZGz.jpg",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.awin1.com/cread.php?awinmid=17629&awinaffid=667997&ued=https://www.casasbahia.com.br/escova-secadora-cadence-rouge-style-esc700-127v-1515113217.html",
      short_url: "https://bit.ly/3HGDOHV",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "escovasecadoracadencerougestyleesc700127v",
      is_image_social: true,
      resize_image_tam: null,
      alertcomment: 1,
      likes: [1214, 445, 2, 10, 215563, 221360],
    },
    {
      id: 31388,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/06/Rectangle_413_4.png",
        name: "Shoptime",
        slug: "shoptime",
        url: "https://www.shoptime.com.br/",
      },
      freight: null,
      warning: null,
      user_fake: {
        username: "Jonhy Everton",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-09-01_at_09.16.15.jpeg",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Supermercado",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T20:57:28.543581-03:00",
      saved: [],
      title: "Sabão Liquido Brilhante Delicadeza Total Coco 3L",
      slug: "sabao-liquido-brilhante-delicadeza-total-coco-3l",
      old_price: "34.99",
      price: "26.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_12_odNg8O3.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.awin1.com/cread.php?awinmid=22194&awinaffid=902797&ued=https://www.shoptime.com.br/produto/1960474342",
      short_url: "https://bit.ly/3iTgKeB",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "sabaoliquidobrilhantedelicadezatotalcoco3l",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 2,
      likes: [10],
    },
    {
      id: 31387,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "Jonhy Everton",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-09-01_at_09.16.15.jpeg",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T20:54:13.197327-03:00",
      saved: [],
      title: "Kit 3 Bolsas Média Pequena e Carteira Couro Sintético ShopBag",
      slug: "kit-3-bolsas-media-pequena-e-carteira-couro-sintetico-shopbag",
      old_price: "129.99",
      price: "99.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/kit-3-bolsas-media-pequena-e-carteira-couro-sintetico-shopbag.png",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url: "https://www.amazon.com.br/dp/B09RKQY7CQ/?tag=parceiropechi-20",
      short_url: "https://amzn.to/3Y9nODY",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "kit3bolsasmediapequenaecarteiracourosinteticoshopbag",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 14,
      likes: [10],
    },
    {
      id: 30684,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "jonhyeverton",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-09-01_at_09.16.15_pY3S8pH.jpeg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T20:51:32.682794-03:00",
      saved: [],
      title: "Chinelo Top Animals, Havaianas, Feminino",
      slug: "chinelo-top-animals-havaianas-feminino-exk8",
      old_price: "23.99",
      price: "18.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/71oD-VxmRL._AC_SL1000_.jpg",
      image_social: null,
      image_real: null,
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/Chinelo-Animals-Havaianas-Feminino-Branco/dp/B094PV267S/?tag=parceiropechi-20",
      short_url: "https://amzn.to/3gQYP7I",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "chinelotopanimalshavaianasfeminino",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 9,
      likes: [216064, 216983, 10],
    },
    {
      id: 31386,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "laryssa_mfelix",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/179491832_721224289258970_9223007346925788281_n.jpg",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Bebidas",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T20:51:19.544124-03:00",
      saved: [],
      title:
        "Perfume Importado Paris Elysees Eau De Toilette Masculino Vodka Limited Edition 100ml",
      slug: "perfume-importado-paris-elysees-eau-de-toilette-masculino-vodka-limited-edition-100ml",
      old_price: "69.00",
      price: "54.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/perfume-importado-paris-elysees-eau-de-toilette-masculino-vodka-limited-edition-100ml.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_WHATS_A_15_VTwwjZ9_OzNUbqG_LmSFAJ2_QMRfqUQ_ENkL6oE_ER52O4A_QhccK1q_z9OJ2Vt.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/real/C%C3%B3pia_de_WHATS_A_15.png",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/Vodka-Limited-Masculino-Paris-Elysees/dp/B008VDH6W8/?tag=parceiropechi-20",
      short_url: "https://amzn.to/3HlAPo1",
      coupon: "",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: true,
      friend_pechinchou: true,
      treated_title:
        "perfumeimportadopariselyseeseaudetoilettemasculinovodkalimitededition100ml",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 12,
      likes: [10, 32104],
    },
    {
      id: 30680,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/19/Amazon.png",
        name: "Amazon",
        slug: "amazon",
        url: "https://www.amazon.com.br/",
      },
      freight: "Frete Grátis Amazon Prime",
      warning: null,
      user_fake: {
        username: "leofabricio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/122964120_3789462247739716_4153710995915978761_n.jpg",
      },
      user: {
        username: "cleitonaguiar",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/WhatsApp_Image_2022-04-14_at_21.03.41.jpeg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "À vista",
      total_comment: 0,
      created_at: "2022-12-09T20:37:36.666656-03:00",
      saved: [],
      title: "Rasteira You Metalic, Havaianas, Feminino",
      slug: "rasteira-you-metalic-havaianas-feminino",
      old_price: "55.99",
      price: "34.90",
      image:
        "https://admin.pechinchou.com.br/media/img/products/rasteira-you-metalic-havaianas-feminino.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_WHATS_A_49_mlP5gqu_AYoCSWc_HnrkiFW_rbTF0no_Bw6R0Be_ASrZmCK_bDkTVUO.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/real/C%C3%B3pia_de_WHATS_A_49.png",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://www.amazon.com.br/dp/B094PV11YP?th=1&psc=1&tag=parceiropechi-20",
      short_url: "https://amzn.to/3iw4pwF",
      coupon: "",
      warning_temp: null,
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: false,
      exclusive: false,
      whatsapp: false,
      telegram: false,
      instagram: false,
      facebook: false,
      friend_pechinchou: false,
      treated_title: "rasteirayoumetalichavaianasfeminino",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 11,
      likes: [10],
    },
    {
      id: 31385,
      store: {
        logo: "https://admin.pechinchou.com.br/media/img/store/11/06/Rectangle_413_10.png",
        name: "Centauro",
        slug: "centauro",
        url: "https://www.centauro.com.br/",
      },
      freight: "Frete Grátis todo o Brasil",
      warning: null,
      user_fake: {
        username: "leofabricio",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2022/122964120_3789462247739716_4153710995915978761_n.jpg",
      },
      user: {
        username: "Henrique77",
        image:
          "https://admin.pechinchou.com.br/media/imgUsers/2021/pp_kn2MEOM.jpg",
      },
      subcategory: {
        category: {
          name: "Moda, Beleza e Perfumaria",
        },
      },
      form_payment: "Parcelado",
      total_comment: 0,
      created_at: "2022-12-09T20:35:02.652952-03:00",
      saved: [],
      title: "Tênis Fila Racer Marker Feminino - Preto+Pink",
      slug: "tenis-fila-racer-marker-feminino-pretopink",
      old_price: "399.99",
      price: "254.99",
      image:
        "https://admin.pechinchou.com.br/media/img/products/Screenshot_11_fcTffdB.png",
      image_social:
        "https://admin.pechinchou.com.br/media/img/products/social/C%C3%B3pia_de_WHATS_A_14_rpEoytR_aQd0Osl_0DMWP8A_hHBdVfg_jcy7B4x_sodq1yA_xv9zDIZ_VFpV19D_gVuJeBA.jpg",
      image_real:
        "https://admin.pechinchou.com.br/media/img/products/real/C%C3%B3pia_de_WHATS_A_14_dJQWrs2.png",
      image_insta: null,
      image_four_promotion: null,
      status: "ACTIVE",
      long_url:
        "https://click.linksynergy.com/deeplink?id=ILc7vlXm*ug&mid=39887&murl=https://www.centauro.com.br/tenis-fila-racer-marker-feminino-975812.html#cor=FP",
      short_url: "https://bit.ly/3Y9lkp8",
      coupon: "TENISCERTO15",
      warning_temp: "",
      ame: false,
      ame_attribute: null,
      is_any_text_price: false,
      any_text_price: "",
      relevant: true,
      exclusive: false,
      whatsapp: true,
      telegram: true,
      instagram: true,
      facebook: true,
      friend_pechinchou: true,
      treated_title: "tenisfilaracermarkerfemininopretopink",
      is_image_social: false,
      resize_image_tam: null,
      alertcomment: 13,
      likes: [10],
    },
  ];
  const page = Number(req.query.page);

  if (typeof page == "number" && page >= 1) {
    var ofertas = await axios.get(`https://admin.pechinchou.com.br/api/v2/produto/?page=${page}`)
      .then(res => res.data)
      .then(res => res.results)
  }
  if (page > 1) {
    ofertasRef.map((p: any) => ofertas.push(p));
  }

  return res.status(200).json(ofertas);
}
